### PR TITLE
adding presentation for week 6

### PR DESCRIPTION
**Pull request by NickPapacostas**

### CODE REVIEW

**Comment by kostasx** [comment]
Hello @NickPapacostas. Have you checked: https://github.com/SocialHackersCodeSchool/JavaScript/blob/master/teacher-prep/GUIDELINES.md 
?

**Comment by NickPapacostas** [comment]
@kostasx I'm adding the contenteditable and a few semicolons (we should discuss this rule i think) did you notice anything else? And thanks for sharing, I should have read them earlier!

**Comment by kostasx** [comment]
I think the pathnames on the Reveal initialization section should be updated also.

**Comment by NickPapacostas** [comment]
Thanks dude! I think it's good now

**Pull request merged**
